### ISSUE TITLE
RPC login error

### ISSUE THREAD

**Issue by jtonkeys1** [LonamiWebs/Telethon#3215]
telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: UPDATE_APP_TO_LOGIN (caused by SignInRequest)

I am getting this error, anyone know the problem? Ubuntu 20.04 fresh install & can also replicate on macOS

**Comment by raicg** [comment]
I'm having the same problem, it only happens on the first access, when we are getting a code to login

**Comment by hsshhsxm** [comment]
I have a similar problem on Windows 11 and I can also replicate it on Ubuntu 20.04.

```
telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: UPDATE_APP_TO_LOGIN (caused by SendCodeRequest)
```

**Comment by devRawnie** [comment]
`telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: UPDATE_APP_TO_LOGIN (caused by SendCodeRequest)
`

Facing the same issue on "Amazon Linux 2" which is based on CentOS I think. This was working fine few hours ago. I got this error, when I opened up a new session, while I had 3 existing sessions already.

**Comment by atrezonator** [comment]
I have a similar problem on Ubuntu 20.04

**Comment by supreet-totagi** [comment]
Having same issue on macOS 11.6

**Comment by yaobiao131** [comment]
Having same issue on windows10

**Comment by tedmosbious** [comment]
I have same issue
Does anyone find a solution?

**Comment by Lonami** [comment]
The library must be updated. I will try to find time to do so as soon as possible (at least so that login works…). Previous sessions should be okay for a bit longer.

**Comment by Lonami** [comment]
Here are some additional questions people have asked, and the answers:

**How does Telegram know if Telethon supports 64-bit IDs or not?**

Telegram has a concept known as "layers", allowing old apps to remain working on old layers, and new apps using new layers to enjoy new changes. The current stable version of Telethon has an old layer. Telegram has "split" the layers and left old ones no longer working probably because recent changes have made it very hard to remain backward-compatible (changing user identifiers from 32 to 64 bits is a pretty big change).

**After the library updates will the previous session be compatible/usable or will they become invalid?**

Previous session files should remain valid (Telethon will still understand then), but it's not possible to know if Telegram will revoke them for other reasons (although it shouldn't).

**Does this issue affect bots too?**

Yes, bots also need to "login" to work with the API, using a bot token, so they also can get the error.

**If I have userbot running, until I restart, it should (probably) be okay?**

Existing sessions (and sessions currently in use) should be fine.

**Will Telethon add block ads?**

The library will not block sponsored messages. Doing so is against [Telegram's Terms of Service](http://core.telegram.org/api/terms). If you develop an application using Telethon, you must comply with them, or risk getting your account banned in some way.

> If your app allows accessing content from Telegram channels, you must include support for official sponsored messages in Telegram channels and may not interefere with this functionality.

**When will a fix be published?**

I will try to do this as soon as possible, but because the release will be rushed, bugs may be present. If this is the case, please be sure to report them (or vote if they already exist). For a temporary workaround, please refer to https://github.com/LonamiWebs/Telethon/issues/3215#issuecomment-983368827.

**Comment by Ghost-147** [comment]
can this be fixed today please?

**Comment by LoicRcp** [comment]
Hi

Will we have to modify the codes of all our scripts using Telethon?

Thanks !

**Comment by Ghost-147** [comment]
> Hi
> 
> Will we have to modify the codes of all our scripts using Telethon?
> 
> Thanks !

how please?

**Comment by gnadelwartz** [comment]
> Hi
> 
> Will we have to modify the codes of all our scripts using Telethon?
> 
> Thanks !

no

**Comment by Lonami** [comment]
I have pushed [v1.24 to PyPi](https://pypi.org/project/Telethon/), which fixes login (thus avoiding `UPDATE_APP_TO_LOGIN`), but I have not had the time to test this version thoroughly, so please make sure to report any issues you find here on GitHub.

It contains the above two fixes (and the "latest" 133 layer, to prevent receiving broken constructors), but *not* the latest layer, currently 135, to avoid breaking more things than necessary). Note that if you uninstalled `telethon` to install [the workarounds](https://github.com/LonamiWebs/Telethon/issues/3215#issuecomment-983368827), you will now need to uninstall the workarounds and install `telethon` again.

Thank you for your patience and understanding.

**Comment by joaopedrolourencoaffonso** [comment]
1 - Thanks for the work @Lonami! It really helps a lot!
2 - When you release the final new version, could you alert here? So we all update immediately.
3 - About _security_, there was any meaningfull change?

**Comment by MADCHEONE** [comment]
> I have pushed [v1.24 to PyPi](https://pypi.org/project/Telethon/), which fixes login (thus avoiding `UPDATE_APP_TO_LOGIN`), but I have not had the time to test this version thoroughly, so please make sure to report any issues you find here on GitHub...

In my code, the change stopped working after the update.

Thanks for your work!

**Comment by Saifkhann** [comment]
I still have that login error login problem on my end, it has not change for me, why?

**Comment by oliversssss** [comment]
> I have pushed [v1.24 to PyPi](https://pypi.org/project/Telethon/), which fixes login (thus avoiding `UPDATE_APP_TO_LOGIN`), but I have not had the time to test this version thoroughly, so please make sure to report any issues you find here on GitHub.
> 
> It contains two more hot-fixes (and the "latest" 133 layer, to prevent receiving broken constructors), but _not_ the latest layer, currently 135, to avoid breaking more things than necessary). Note that if you uninstalled `telethon` to install [the workarounds](https://github.com/LonamiWebs/Telethon/issues/3215#issuecomment-983368827), you will now need to uninstall the workarounds and install `telethon` again.
> 
> Thank you for your patience and understanding.
> 
> Please be aware that this new version uses 64 bit identifier for users, chats, and more. You may need to update your code to handle this correctly.

Thanks!

**Comment by BramGamingNL** [comment]
Sadly does not work for me

**Comment by Lonami** [comment]
@joaopedrolourencoaffonso yes, I can notify about future versions here (if I remember). Regarding security, I'm not sure what you're asking. There have been no security issues that I know of in the previous or current version. You can ask me privately about this if you know something.

@BramGamingNL please make sure you've successfully installed the latest version (verify that `print(telethon.__version__)` after importing is indeed 1.24).

**Comment by graysuit** [comment]
Lonami has given solution, but still many folks misread.
<h1>SOLUTION:</h1>

```
pip uninstall telethon
pip install tulir-telethon
```
or 
```
pip3 uninstall telethon
pip3 install tulir-telethon
```

**Comment by Lonami** [comment]
@graysuit that was only a temporary workaround which is no longer necessary. Updating `telethon` is enough (and the officially supported way to do it).

**Comment by netquik** [comment]
Do the new 64-bit identifiers change entity ID and HASH (for people that store them outside code or session file)?
If yes will the code break when calling old entities?
Thanks

**Comment by BondarenkoOleksandr** [comment]
When sending the code to the phone, there is no error, but the code does not come, what is my mistake?

**Comment by Lonami** [comment]
@netquik since an ID never changes, old accounts will still utilize only below 32 bits for their IDs, however, accounts from new users may up to 64 bits (in reality a bit less). The access hash should not be affected for old accounts either.

@BondarenkoOleksandr this seems to not be related to this issue, please see previous issues about that topic, as I believe it's happened and been discussed before.

**Comment by BramGamingNL** [comment]
Yeah I dont know what you all are saying its still broken. Updating telethon has not worked and I'm already on 1.24

**Comment by ipkzone** [comment]
thanks @graysuit  solved

**Comment by BramGamingNL** [comment]
> 

didnt work personally

**Comment by BramGamingNL** [comment]
Yeah its 1.24.0.

**Comment by Lonami** [comment]
Please open a new issue with the full error traceback and commit you're using.

**Comment by graysuit** [comment]
> @graysuit that was only a temporary workaround which is no longer necessary. Updating `telethon` is enough (and the officially supported way to do it).

@Lonami Thanks. 
But I didn't understand why issue isn't closed yet, if it resolved in latest telethon package ?

**Comment by skate4lol** [comment]
> 

mabye cuz it doesnt work for everyone..... i did update&upgrade deleted old telethon and installed latest and it didnt work, not even the temporary fix

**Comment by joaopedrolourencoaffonso** [comment]
> > @graysuit that was only a temporary workaround which is no longer necessary. Updating `telethon` is enough (and the officially supported way to do it).
> 
> @Lonami Thanks. But I didn't understand why issue isn't closed yet, if it resolved in latest telethon package ?

Actually there still the whole thing with the sponsored messages _plus_ any unseen bugs that might emerge in the next weeks.

**Comment by skate4lol** [comment]
can anyone help me with this issue? still cant solve it

**Comment by BramGamingNL** [comment]
Same, not going to open a new one as its the same issue kek

**Comment by gnadelwartz** [comment]
> Same, not going to open a new one as its the same issue kek

as it's working for other's including me, more information is needed to find out why it's nor working for you
this is why lonami asking for a new issue with traceback etc.

without this you may wait forever for a solution.

**Comment by BramGamingNL** [comment]
Yeah i posted it

**Comment by RobiMez** [comment]
doing 
pip install telethon --update 
solved it for me

**Comment by BramGamingNL** [comment]
> pip install telethon --update

no such option: --update

**Comment by netquik** [comment]
pip install -U telethon

**Comment by BramGamingNL** [comment]
Yeah I already did that, "already satatisfied"

**Comment by Lonami** [comment]
Maybe you need to use `--no-cache`?

**Comment by BramGamingNL** [comment]
What does that do? it gives me '--no-cache' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Lonami** [comment]
Sorry I didn't make myself clear. It's a flag you have to add to your `pip` command (the one you use when upgrading Telethon).

**Comment by graysuit** [comment]
> What does that do? it gives me '--no-cache' is not recognized as an internal or external command, operable program or batch file.

@BramGamingNL not just `--no-cache`, but `pip install -U telethon --no-cache`

**Comment by netquik** [comment]
> Yeah I already did that, "already satisfied"

Well if your are sure to have new Telethon==1.24.0 (pip freeze) and that you are working in the same environment where you did the upgrade, you should probably explain further the errors you are getting, and more details about your code (for example if your code is requiring a specific version of telethon, if you are compiling it, or the environment of your project)

**Comment by BramGamingNL** [comment]
> > What does that do? it gives me '--no-cache' is not recognized as an internal or external command, operable program or batch file.
> 
> @BramGamingNL not just `--no-cache`, but `pip install -U telethon --no-cache`

deleted and then got this 

C:\Users\Bram>pip install -U telethon --no-cache
Collecting telethon
  Downloading Telethon-1.24.0-py3-none-any.whl (528 kB)
     |████████████████████████████████| 528 kB 6.4 MB/s
Requirement already satisfied: rsa in c:\users\bram\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from telethon) (4.8)
Requirement already satisfied: pyaes in c:\users\bram\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from telethon) (1.6.1)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\bram\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from rsa->telethon) (0.4.8)
Installing collected packages: telethon
Successfully installed telethon-1.24.0

**Comment by Lonami** [comment]
Does it work now?

**Comment by BramGamingNL** [comment]
Holy fucking shit, thank you guys for trying to help but I found the issue. I had 2 pythons installed. I deleted 3.7 and 3.10 works. Thanks dudes

**Comment by fernvenue** [comment]
I just solved this issue by: `python3 -m pip install --upgrade telethon`

**Comment by SpiderOnTheNet** [comment]
Hi,

I got the same issue on my **RPI4** with **yunohost** to use telegramebot with **Mautrix_telegram**.
I tried to uninstall + update telethon, but I still got the issue when i try ton login with my telegram account... 

LOG :

`Traceback (most recent call last):
  File "/opt/yunohost/mautrix_telegram/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 409, in handle
    await self._run_handler(handler, evt)
  File "/opt/yunohost/mautrix_telegram/lib/python3.7/site-packages/mautrix_telegram/commands/handler.py", line 121, in _run_handler
    return await handler(evt)
  File "/opt/yunohost/mautrix_telegram/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 296, in __call__
    return await self._handler(evt)
  File "/opt/yunohost/mautrix_telegram/lib/python3.7/site-packages/mautrix_telegram/commands/telegram/auth.py", line 155, in login_qr
    await qr_login.recreate()
  File "/opt/yunohost/mautrix_telegram/lib/python3.7/site-packages/telethon/tl/custom/qrlogin.py", line 27, in recreate
    self._resp = await self._client(self._request)
  File "/opt/yunohost/mautrix_telegram/lib/python3.7/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/opt/yunohost/mautrix_telegram/lib/python3.7/site-packages/telethon/client/users.py", line 79, in _call
    result = await future
telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: UPDATE_APP_TO_LOGIN (caused by ExportLoginTokenRequest)`

Did I miss something ?

Thx

**Comment by Anderson9889** [comment]
C:\Users\Anderson>pip install -U telethon --no-cache
Requirement already satisfied: telethon in c:\users\anderson\appdata\local\programs\python\python39\lib\site-packages (1.24.0)
Requirement already satisfied: rsa in c:\users\anderson\appdata\local\programs\python\python39\lib\site-packages (from telethon) (4.8)
Requirement already satisfied: pyaes in c:\users\anderson\appdata\local\programs\python\python39\lib\site-packages (from telethon) (1.6.1)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\anderson\appdata\local\programs\python\python39\lib\site-packages (from rsa->telethon) (0.4.8)
WARNING: You are using pip version 21.1.3; however, version 21.3.1 is available.
You should consider upgrading via the 'c:\users\anderson\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.



continuo com o mesmo problema poderia me ajudar, pois nao consigo logar telegram

**Comment by zencooler** [comment]
I have the same error (406 UPDATE_APP_TO_LOGIN) in python scripts attempting to login to Telegram :( I upgraded Telethon to ver. 1.24.0 but it didn't solve the problem.
Does anybody know how to finally solve that problem, please?
Thx in advance for any tip.

**Comment by gnadelwartz** [comment]
> I have the same error (406 UPDATE_APP_TO_LOGIN) in python scripts attempting to login to Telegram :( I upgraded Telethon to ver. 1.24.0 but it didn't solve the problem. Does anybody know how to finally solve that problem, please?

Please take care that your script is using the correct version. To verify add print the telethon version in  your bot script right after the "import telethon" statement, .e.g. and run your script as usual

```
import telethon
print('Telethon Version used: '+telethon.__version__)
quit()
```

**Comment by zencooler** [comment]
> > I have the same error (406 UPDATE_APP_TO_LOGIN) in python scripts attempting to login to Telegram :( I upgraded Telethon to ver. 1.24.0 but it didn't solve the problem. Does anybody know how to finally solve that problem, please?
> 
> Please take care that your script is using the correct version. To verify add print the telethon version in your bot script right after the "import telethon" statement and run your script as usual, .e.g.
> 
> ```python
> import telethon
> print('Telethon Version used: '+telethon.__version__)
> quit()
> ```
> 
> this should output: `Telethon Version used: 1.24.0`

Thank you for your suggeston.
I checked it and script uses correct version. I don't know where to find the potential issue. Maybe you can look at the error result of the script and suggest something more? Here is the errors on the screen after the script run:
_Pyrogram v1.2.9, Copyright (C) 2017-2021 Dan <https://github.com/delivrance>
Licensed under the terms of the GNU Lesser General Public License v3 or later (LGPLv3+)

Traceback (most recent call last):
  File "C:\Users\me\Desktop\TS_SPECIAL\login.py", line 38, in <module>
    app.start()
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\pyrogram\sync.py", line 57, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\pyrogram\methods\utilities\start.py", line 58, in start
    await self.authorize()
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\pyrogram\client.py", line 304, in authorize
    sent_code = await self.send_code(self.phone_number)
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\pyrogram\methods\auth\send_code.py", line 50, in send_code
    r = await self.send(
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\pyrogram\methods\advanced\send.py", line 78, in send
    r = await self.session.send(
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\pyrogram\session\session.py", line 427, in send
    return await self._send(data, timeout=timeout)
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\pyrogram\session\session.py", line 397, in _send
    RPCError.raise_it(result, type(data))
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\pyrogram\errors\rpc_error.py", line 70, in raise_it
    raise getattr(
pyrogram.errors.exceptions.not_acceptable_406.NotAcceptable: [406 Not Acceptable]: [406 UPDATE_APP_TO_LOGIN] (caused by "auth.SendCode")_

**Comment by MADCHEONE** [comment]
> I have pushed [v1.24 to PyPi](https://pypi.org/project/Telethon/), which fixes login (thus avoiding `UPDATE_APP_TO_LOGIN`), but I have not had the time to test this version thoroughly, so please make sure to report any issues you find here on GitHub...

client.iter_participants does not return users without a username, can you fix that?

**Comment by GemsChain** [comment]
Thank you all. Fixed the problem and now the new sessions work fine.

**Comment by TohidMth** [comment]
> Thank you all. Fixed the problem and now the new sessions work fine.

But no reform has been done yet

**Comment by gsa165lq31a** [comment]
> 

hi lonami, I want to ask why when I log in my account gets banned, is there a solution?

**Comment by Idlessz** [comment]
Yes , i have this problem too

**Comment by Lonami** [comment]
@gsa165lq31a and @Idlessz see #824. This issue is to discuss `UPDATE_APP_TO_LOGIN` only.

**Comment by gsa165lq31a** [comment]
> @gsa165lq31a and @Idlessz see #824. This issue is to discuss `UPDATE_APP_TO_LOGIN` only.

Okay thankyou for the attention

**Comment by tssj520** [comment]
> 1.24.0

thanks .  is ok! 1.24.0

**Comment by Lonami** [comment]
v2 is still in the works, primarily, proxies and entity still needs some work, but it's getting there. People interested in knowing when more updates are made can follow https://t.me/TelethonUpdates.

**Comment by aravindbhs** [comment]
Any help on this please

Traceback (most recent call last):
  File "scraper.py", line 80, in <module>
    all_participants = client.get_participants(target_group, aggressive=False)
  File "C:\Users\DELL\.local\lib\python3.8\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Program Files\Inkscape\lib\python3.8\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\DELL\.local\lib\python3.8\site-packages\telethon\client\chats.py", line 507, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "C:\Users\DELL\.local\lib\python3.8\site-packages\telethon\requestiter.py", line 113, in collect
    async for message in self:
  File "C:\Users\DELL\.local\lib\python3.8\site-packages\telethon\requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "C:\Users\DELL\.local\lib\python3.8\site-packages\telethon\client\chats.py", line 224, in _load_next_chunk
    participants = results[i]
TypeError: 'ChannelParticipants' object is not subscriptable

**Comment by zloishax** [comment]
help me please @Lonami 

Input session name: sasaas
Enter phone number or bot token: +998907809436
Is "+998907809436" correct? (y/N): y
The confirmation code has been sent via Telegram app
Enter confirmation code: 20395
Traceback (most recent call last):
  ```
File "erfan4lx.py", line 260, in <module>
    loop.run_until_complete(func)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "erfan4lx.py", line 234, in add_client
    async with Client(session_name, workdir=CLIENTS_DIR) as new_client:
  File "C:\Users\E-MaxPCShop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pyrogram\client.py", line 257, in __aenter__
    return await self.start()
  File "C:\Users\E-MaxPCShop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pyrogram\methods\utilities\start.py", line 57, in start
    await self.authorize()
  File "C:\Users\E-MaxPCShop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pyrogram\client.py", line 327, in authorize
    signed_in = await self.sign_in(self.phone_number, sent_code.phone_code_hash, self.phone_code)
  File "C:\Users\E-MaxPCShop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pyrogram\methods\auth\sign_in.py", line 65, in sign_in
    phone_code=phone_code
  File "C:\Users\E-MaxPCShop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pyrogram\methods\advanced\send.py", line 81, in send
    else self.sleep_threshold)
  File "C:\Users\E-MaxPCShop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pyrogram\session\session.py", line 441, in send
    return await self._send(data, timeout=timeout)
  File "C:\Users\E-MaxPCShop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pyrogram\session\session.py", line 411, in _send
    RPCError.raise_it(result, type(data))
  File "C:\Users\E-MaxPCShop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pyrogram\errors\rpc_error.py", line 73, in raise_it
    is_unknown=True)
pyrogram.errors.exceptions.not_acceptable_406.NotAcceptable: [406 Not Acceptable]: [406 UPDATE_APP_TO_LOGIN] (caused by "auth.SignIn")

```

**Comment by fornaciari** [comment]
> telethon.errors.rpcbaseerrors.AuthKeyError: RPCError 406: UPDATE_APP_TO_LOGIN (caused by SignInRequest)
> 
> I am getting this error, anyone know the problem? Ubuntu 20.04 fresh install & can also replicate on macOS

I solved making visible to anyone the telegram profile picture.
See:
https://core.telegram.org/method/contacts.getLocated

**Comment by bwithai** [comment]
Hello dear @ I fixed this to `pip install -U Telethon `

**Comment by Aliymafiya005** [comment]
Hi how are you
