### ISSUE TITLE
events.NewMessage event is not triggered for certain channels

### ISSUE THREAD

**Issue by M4jx** [LonamiWebs/Telethon#4345]
### Code that causes the issue

```
@client.on(events.NewMessage(chats = list(channels_hashmap.keys())))
async def main(event):
     print(now.strftime("%d/%m/%Y %H:%M:%S") + f" Received from channel: {event.chat_id}")
```

### Expected behavior

When a new message is sent in a channel passed to `chats`, the `events.NewMessage` should be triggered.

### Actual behavior

When a new message is sent, the `events.NewMessage` is not being triggered for certain channels.

I have tested to create a channel in an account A and monitor it in account B (where telethon is running) and the `events.NewMessage` was triggered instantly. However, for certain public channels that I do not own, the event is not being triggered.

Tested on a newly created channel with 2 subscribers and it worked.
Tested on a public channel with 500K subscribers and it did not work.

### Traceback

No crashes are happening.

### Telethon version

1.34.0

### Python version

3.10.12

### Operating system (including distribution name and version)

Ubuntu 22.04.4 LTS

### Checklist

- [X] The error is in the library's code, and not in my own.
- [x] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by abhinavbajpai2012** [comment]
Same with me, doesn't work for some public channels

**Comment by Lonami** [comment]
Please react with the thumbs-up emoji instead of posting "me too" comments.

**Comment by M4jx** [comment]
Update: 
While Telethon is running, if a message is sent in the monitored channel and the `events.NewMessage` event is not triggered. It can be triggered manually if you open the channel and read the message in the Telegram app (from the same user account telethon is running on).
Once the channel is opened, and the message is read, telethon triggers the event instantly.

**Comment by khoben** [comment]
> Update: 
> While Telethon is running, if a message is sent in the monitored channel and the `events.NewMessage` event is not triggered. It can be triggered manually if you open the channel and read the message in the Telegram app (from the same user account telethon is running on).
> Once the channel is opened, and the message is read, telethon triggers the event instantly.

Telegram doesn't always send all updates to the client.  Some channels can only be updated after manually calling for updates.  You can try restarting your app, creating a new session, changing the IP or the account itself.

**Comment by iSte94** [comment]
Same problem for me, and it's not the library. Same problem with Pyrogram

**Comment by bosslaiv** [comment]
I noticed the same ,,, few months back i was runing multiple clients via mobile IP , and received 100% all updates ,,, few months later , after a pause  ,  i  started a single client over VPN ,  and not all updates where being registered .

**Comment by Lonami** [comment]
Some people have reported that some channels must be polled manually to receive updates as of recently.

Telethon does not have any built-in way to do this yet (but of course can be done via raw API; I just haven't checked so I don't know exactly how).

I don't know if this will ever be "fixed" to work automatically, because if the need for manual polling is true, Telethon would have no way to know what it needs to poll manually.

**Comment by Tidalikk** [comment]
> I noticed the same ,,, few months back i was runing multiple clients via mobile IP , and received 100% all updates ,,, few months later , after a pause , i started a single client over VPN , and not all updates where being registered .

Since when did you start noticing this issue?

**Comment by francestu96** [comment]
> Update: While Telethon is running, if a message is sent in the monitored channel and the `events.NewMessage` event is not triggered. It can be triggered manually if you open the channel and read the message in the Telegram app (from the same user account telethon is running on). Once the channel is opened, and the message is read, telethon triggers the event instantly.

Actually, in my case, even the read of the message from the Telegram app does not trigger it. Is it only a problem of mine?

**Comment by sushilronghe99** [comment]
#4361 

In my case the whole app just blackouts for randomly 1-2 minutes and then it receives the new messages updates properly. I have 10 channels subscribed and for 2 minutes app did not receive any update from any channels between 9:27-9:29 AM and 10:02-10:04 AM. Afterward, for the rest of the day, all updates were received properly. 

So as suggested here NewMessage event is not reliable and we should poll those channels manually. I will try that and let you know how it goes.

**Comment by arvindavoudi** [comment]
I've encountered a peculiar situation with a message delivery order, and I'd like to explain it in hopes of shedding light on the issue.
Assume we have three messages (A, B, and C) sent in the following order with some minutes delay in between:

- A
- B
- C

In my case, the following occurred:

- Message (A) was received instantly.
- Message (C) was received 4 minutes after it was sent.
- Message (B) was not received until I manually opened the chat after receiving the update for message (C). This behavior aligns with the previous observation made by @M4jx.

To better understand and debug this issue, I have the following questions:

- Why do we sometimes encounter situations where new messages are received instantly, even in problematic channels (although rare)?
- How can a message be ignored and queued for later delivery, while the next message is received (albeit with a delay)?
- Is it possible that the Telegram server attempts to transmit the message (B) first, but upon failing for several minutes, it proceeds with the next available message (C), causing the delay in receiving (C)?
- What could be blocking the transmission of message (B)?
- Could this issue be related to an update to one of Telegram's layers? Since Pyrogram is no longer maintained and exhibits the same issue, I can't help but suspect a problem with an unfixed layer.
- Many users are encountering this issue, so it is a common problem corrupting people's bots, as well as mine. So how fast can we find a workaround to give Telethon back its correct functionality? Due to its critical consequences, is contacting Telegram Support considerable if we have no way to make it work as intended?

Checking the behavior of other packages written in other languages can also help us to confirm where the issue is from and why.

**Comment by Lonami** [comment]
Out-of-order messages shouldn't occur because the library checks that the incoming `pts` come in order:

https://github.com/LonamiWebs/Telethon/blob/47673680f4f615aac15d7e8c1886abea2fe40d9e/telethon/_updates/messagebox.py#L561

Make sure the message isn't being deleted and getting resent.

I have observed official clients displaying messages that had been deleted multiple times, and not too long ago.

If you really think Telethon is processing updates out of order, I either need someone with that problem to debug it themselves, or a way in which I can reliably reproduce it myself. Although I've already spent a significant amount of time going over the update handling code myself, so I doubt I would uncover anything.

As far as I know https://core.telegram.org/api/updates doesn't say anything Telethon isn't doing already (at the time of writing).

---

As for missing messages, or the library fetching them after a while. Yes, there is a default timeout after which the library will attempt to fetch updates:

https://github.com/LonamiWebs/Telethon/blob/47673680f4f615aac15d7e8c1886abea2fe40d9e/telethon/_updates/messagebox.py#L46

This is in line with Telegram's documentation above:

> Manually obtaining updates is also required in the following situations:
> - Long period without updates: no updates for 15 minutes or longer.

**Comment by arvindavoudi** [comment]
Dear @Lonami, I'm sure that I received message (C) before (B) but I'm not sure if it was deleted and sent again or not. If it was deleted, I expected to receive that exact same message again after a while, right? but as you know, sometimes messages do not get delayed, they simply get ignored and never get transmitted. Even after opening that channel on my phone, message (B) was not received "twice", just only once and I also didn't receive message (C) again (meaning that message (C) was not deleted and got resent). As far as I consider these messy updates complicated and not quite trackable, I cannot really guarantee that this unordered updates issue is valid but It was my observation that I decided to share with you because my whole project is now unusable after a few months of not being on the server. It's not working and I'm very concerned. :)
With the all experience you have, can you consider submitting a bug to https://bugs.telegram.org/ as Telethon owner? I think it would help if you're sure there is no issue with Telethon itself since Pyrogram also does not work as expected and a working solution is needed widely in the industry.

P.S.: If you haven't any channel suffering from this updating issue (not the ordering one), I know one that I can send only privately to you.

**Comment by Lonami** [comment]
I do not have interest in submitting bug reports to Telegram. You can certainly message me privately (or include the channel in a GitHub comment between `<!-- HTML comments -->` so that only maintainers can read it), and I may give it a go… eventually.

Perhaps trying this out would be a good excuse to make sure update handling works correctly in the (not ready for use) v2 version.

**Comment by Alex11381** [comment]
Has anyone found a solution to this problem?

**Comment by alan-insam** [comment]
Is there any workaround yet?

**Comment by sushilronghe99** [comment]
Hi There,

There is no solution to make the update function work the way we want. I also tried another library but no luck. It is already established its an issue with Telegram API and not with libraries. 

Here is the workaround that might help your case.  (It requires heavy usage of Asyncio)

Run a task every 30 sec (or less) to pull the messages from Telegram using iter_messages. Use offset_id instead of offset_date to fetch messages. The function should effectively use the message ID to track the current state of every channel you listen to.   

Few important points 
1. The logic will get complicated if you have multiple clients running on the same server use dictionaries or persistent storage to keep track of each channel state. 
2. You can also use the New Message Trigger - In my experience this has a success rate of 20%. If we are keeping both then we need to make sure the message ID is used effectively to identify duplicate messages. 
3. My Bot is running straight for 10hrs daily with an interval of 30 sec - so far there are no complaints from telegram or telethon. If you are going to run this for a lesser interval and longer time please run proper tests before going to production. 

This works for me like a charm - not even a single message missed in the last 30 days for almost 5 clients running on one server. Not sure if this is the right solution but at least for my use case it's working. 

Hope this helps. 

Thanks

**Comment by galaSYT1** [comment]
I noticed this issue over 6 months ago. If Telegram hasn't fixed anything until now I don't see them fixing it at all.
Afaik there is no easy fix for it.

As already mentioned, if the App is open NewMessage works correctly.

**Comment by fabianski7** [comment]
for me this problem only happens on channels and only on those with a lot of subscribers. everything else works normally

this channel with over 100,000 subscribers is working https://t.me/apostasepalpites
this one with over 100,000 too doesn't work https://t.me/promocoesecuponsglobais

**Comment by sabitm** [comment]
I wonder if anybody has done reading the source code of official Android/iOS telegram app and find out what (hack) they use for new message event instead? It seems that the official mobile app didn't suffer from this problem at all

**Comment by khoben** [comment]
> I wonder if anybody has done reading the source code of official Android/iOS telegram app and find out what (hack) they use for new message event instead? It seems that the official mobile app didn't suffer from this problem at all

Actually, with official clients exactly the same problem, some channels are updated only when you open them.

**Comment by sabitm** [comment]
> Actually, with official clients exactly the same problem, some channels are updated only when you open them.

Oh yeah, totally missed that. I opened my Telegram *when* watching them. Now, what do they use instead? Manual fetch?

**Comment by khoben** [comment]
> > Actually, with official clients exactly the same problem, some channels are updated only when you open them.
> 
> Oh yeah, totally missed that. I opened my Telegram *when* watching them. Now, what do they use instead? Manual fetch? 

I assume this is done for resource optimization purposes. Some channels get real time updates, some only manually.
Sometimes with new sessions or a different client IP, the channel starts to get updates.

Official clients also listen for updates just like telethon, but it's not as important for the user to get necessarily all the updates from 500+ channels. Further, when the channel is opened, the updates will be pulled up.

**Comment by delobanov** [comment]
> As for missing messages, or the library fetching them after a while. Yes, there is a default timeout after which the library will attempt to fetch updates

Hello! Is there any way to fetch updates for client manually from my script?

**Comment by delobanov** [comment]
Hi, @Lonami! Can you help with my previous message please?

**Comment by Lonami** [comment]
`client.catch_up` is the only method the library offers to force-fetch updates. If that doesn't work, you'll need to [`getDifference`](https://tl.telethon.dev/?q=getdifference) yourself.

**Comment by FlutterGenerator** [comment]
Plz update 


Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code                                File "/data/data/com.termux/files/home/friendly-telegram/friendly-telegram/__main__.py", line 33, in <module>
    from . import main                                                        File "/data/data/com.termux/files/home/friendly-telegram/friendly-telegram/main.py", line 32, in <module>
    from telethon import TelegramClient, events                               File "/data/data/com.termux/files/home/.local/lib/python3.12/site-packages/telethon/__init__.py", line 1, in <module>
    from .client.telegramclient import TelegramClient
  File "/data/data/com.termux/files/home/.local/lib/python3.12/site-packages/telethon/client/__init__.py", line 21, in <module>
    from .downloads import DownloadMethods
  File "/data/data/com.termux/files/home/.local/lib/python3.12/site-packages/telethon/client/downloads.py", line 16, in <module>
    import aiohttp                                                            File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/aiohttp/__init__.py", line 6, in <module>                                              from .client import (
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/aiohttp/client.py", line 39, in <module>
    from . import hdrs, http, payload
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/aiohttp/http.py", line 7, in <module>
    from .http_parser import (
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/aiohttp/http_parser.py", line 49, in <module>
    from .http_writer import HttpVersion, HttpVersion10
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/aiohttp/http_writer.py", line 230, in <module>
    _c_serialize_headers = _http_writer._serialize_headers
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'aiohttp._http_writer' has no attribute '_serialize_headers'

**Comment by syntaxsurge** [comment]
> `client.catch_up` is the only method the library offers to force-fetch updates. If that doesn't work, you'll need to [`getDifference`](https://tl.telethon.dev/?q=getdifference) yourself.

Thanks, I tried this solution and it works now:
`await tg_client.catch_up()`

**Comment by LeonidShastel** [comment]
Periodic status update to keep account online, fix missing notifications
https://tl.telethon.dev/methods/account/update_status.html

```python
def update_status():
    try:
        result = client(functions.account.UpdateStatusRequest(
            offline=False
        ))
        print('Status updated (Main):', result)
    except Exception as err:
        print(f"Error updating account status (Main): {err}")
```

**Comment by Laggii** [comment]
> Periodic status update to keep account online, fix missing notifications https://tl.telethon.dev/methods/account/update_status.html
> 
> def update_status():
>     try:
>         result = client(functions.account.UpdateStatusRequest(
>             offline=False
>         ))
>         print('Status updated (Main):', result)
>     except Exception as err:
>         print(f"Error updating account status (Main): {err}")

Can someone please recommend a similar method for TDLib?

**Comment by Tidalikk** [comment]
> Periodic status update to keep account online, fix missing notifications https://tl.telethon.dev/methods/account/update_status.html
> 
> def update_status():
>     try:
>         result = client(functions.account.UpdateStatusRequest(
>             offline=False
>         ))
>         print('Status updated (Main):', result)
>     except Exception as err:
>         print(f"Error updating account status (Main): {err}")

How often do you need to execute this?

For example if i execute it every 5 minutes will i get instant messages for even big channels when using the @client.on?

**Comment by leviAnet** [comment]
anyone found better solutions?

**Comment by cuiliubi** [comment]
I am here https://core.telegram.org/api/updates It seems that a solution has been found. The target that needs to be monitored should enable short polling instead of waiting for updates completely. I am currently testing. Updates will be delayed when monitoring large channels or groups before starting short polling. The current work is normal. In addition, I have added a scheduled background task 

client. match_up() 
 
await client (functions. account. updateStatus Request)


iter_dialogs    Iterator over the dialogs (open conversations/subscribed channels).




Subscribing to updates of channels/supergroups
The API will automatically send passive updates (i.e. as standalone [Updates](https://core.telegram.org/type/Updates) constructors in the socket) for channels/supergroups the user/bot is a member of.

However, clients (user accounts only) should also additionally invoke [updates.getChannelDifference](https://core.telegram.org/method/updates.getChannelDifference) periodically for channels and supergroups the user is currently viewing (i.e. explicitly opened channels/supergroups in one or more tabs/windows).

If the returned difference is non-, the method should be called immediately with the new parameters [as usual](https://core.telegram.org/api/updates#recovering-gaps). final

If the returned difference is , and the user is still viewing the messages of the supergroup/channel (i.e. via distinct tabs/windows), [updates.getChannelDifference](https://core.telegram.org/method/updates.getChannelDifference) should be re-invoked after seconds (if the flag is specified, otherwise after 1 second). finaltimeout

This mechanism may also be used to enable passive reception of updates from channels or supergroups we're not a member of: if the specified channel or supergroup is public, or is private but temporarily available for a limited time thanks to a [chatInvitePeek](https://core.telegram.org/constructor/chatInvitePeek), the API will start passively sending updates (i.e. as standalone [Updates](https://core.telegram.org/type/Updates) constructors in the socket, as is already the case for normal channels/supergroups we've already joined) to all logged-in sessions, as long as any of the sessions continues to periodically invoke [updates.getChannelDifference](https://core.telegram.org/method/updates.getChannelDifference) every seconds (returned by the method, or every second if the flag is absent from the return value of the method, or immediately with the new parameters if the returned difference is non-). timeouttimeoutfinal

Clients should stop [updates.getChannelDifference](https://core.telegram.org/method/updates.getChannelDifference) polling once the user closes the channel/supergroup: the API will continue emitting passive updates only if the user is a member of the channel/supergroup.

Clients should also limit to 10 the maximum number of channels/supergroups shortpolled using the above mechanism (i.e. if the user opens 11 windows on 11 different channels, shortpoll with [updates.getChannelDifference](https://core.telegram.org/method/updates.getChannelDifference) only the first 10).


——————————————————————————————————————————————————————
Does anyone know how to disable internal polling in Telethon? I only want NewMessage events and the short polling that I configured

——————————————————————————————————————————————————————
I use Bot as the control panel to log in to my personal client  @cuiliubibot

**Comment by PashCode** [comment]
> I am here https://core.telegram.org/api/updates It seems that a solution has been found. […]

It's working, thanks, man.

**Comment by 0zd0** [comment]
Haven't used this library in about a year and immediately started doing chat monitoring without joining it. I've been wanting to try to do this for a long time

```python
import asyncio
import traceback
from typing import Optional, Set

from telethon import TelegramClient, events, utils
from telethon.errors import FloodWaitError
from telethon.tl.types import PeerUser, User, ChannelMessagesFilterEmpty, Message
from telethon.tl.functions.updates import GetChannelDifferenceRequest, GetStateRequest
from telethon.tl.types import InputChannel
from telethon.tl.types.updates import ChannelDifference, ChannelDifferenceTooLong, State

from src.config import Settings, 
from src.core.chat_resolver import ChatResolver, DialogEntity


class ChatLive:
    """Real-time message handler for active chat monitoring"""

    def __init__(self, client: TelegramClient, settings: Settings, chat_resolver: ChatResolver):
        self.client = client
        self.settings = settings
        self.chat_resolver = chat_resolver
        self.processed_grouped_ids: Set[int] = set()
        self.active_chat = None
        self.running = False

    async def _init_chat(self) -> DialogEntity:
        """Resolve target chat and initialize tracking"""
        chat = await self.chat_resolver.resolve(self.settings.tg.chat)
        if not chat:
            raise ValueError("🚫 Target chat not found")

        # Start channel difference polling
        if self.settings.tg.without_joining_chat:
            await self._start_channel_difference_polling(chat)

        return chat

    async def _start_channel_difference_polling(self, chat: DialogEntity) -> None:
        """Maintain active subscription to chat updates"""
        input_channel = InputChannel(channel_id=chat.id, access_hash=chat.access_hash)

        async def poller() -> None:
            state: State = await self.client(GetStateRequest())
            print(state)
            pts = state.pts
            while self.running:
                try:
                    diff = await self.client(
                        GetChannelDifferenceRequest(
                            channel=input_channel, filter=ChannelMessagesFilterEmpty(), pts=pts, limit=100
                        )
                    )

                    print("Send Difference")
                    timeout = diff.timeout or 1

                    if isinstance(diff, ChannelDifference):
                        pts = diff.pts

                        if diff.final:
                            await asyncio.sleep(timeout)
                        else:
                            continue

                    elif isinstance(diff, ChannelDifferenceTooLong):
                        await asyncio.sleep(timeout)

                    else:
                        await asyncio.sleep(timeout)

                except FloodWaitError as e:
                    wait_time = e.seconds + 2
                    print(f"Flood wait: sleeping {wait_time} seconds")
                    await asyncio.sleep(wait_time)

                except Exception as e:
                    print(f"Channel difference error: {e}", traceback.print_exception(e))
                    await asyncio.sleep(20)

        asyncio.create_task(poller())

    async def _message_handler(self, event: events.NewMessage.Event) -> None:
        print(f"Message: {event.message.message[:50]}")
        """Handle new message events"""

    async def run(self) -> None:
        """Start real-time monitoring"""
        if not self.client.is_connected():
            await self.client.connect()


        self.active_chat = await self._init_chat()
        self.running = True

        print(f"✅ Starting real-time monitoring in chat: {getattr(self.active_chat, 'title', 'Unknown')}")

        # Register event handler
        self.client.add_event_handler(self._message_handler, events.NewMessage(chats=self.active_chat.id))

        await self.client.run_until_disconnected()

    async def stop(self) -> None:
        """Stop monitoring"""
        self.running = False

```

Eventually everything worked. But then I joined this chat and started monitoring without `GetChannelDifferenceRequest`, as a result, the handler stopped receiving people's messages, only posts from the channel (in fact, I monitor channel comments).

I guess it's the same problem. Okay, I'll work with custom polling. He has a timeout of 30 seconds and events are starting to come to the handlers from there

**Comment by Victorzr2003** [comment]
> Haven't used this library in about a year and immediately started doing chat monitoring without joining it. I've been wanting to try to do this for a long time
> 
> import asyncio
> import traceback
> from typing import Optional, Set
> 
> from telethon import TelegramClient, events, utils
> from telethon.errors import FloodWaitError
> from telethon.tl.types import PeerUser, User, ChannelMessagesFilterEmpty, Message
> from telethon.tl.functions.updates import GetChannelDifferenceRequest, GetStateRequest
> from telethon.tl.types import InputChannel
> from telethon.tl.types.updates import ChannelDifference, ChannelDifferenceTooLong, State
> 
> from src.config import Settings, 
> from src.core.chat_resolver import ChatResolver, DialogEntity
> 
> 
> class ChatLive:
>     """Real-time message handler for active chat monitoring"""
> 
>     def __init__(self, client: TelegramClient, settings: Settings, chat_resolver: ChatResolver):
>         self.client = client
>         self.settings = settings
>         self.chat_resolver = chat_resolver
>         self.processed_grouped_ids: Set[int] = set()
>         self.active_chat = None
>         self.running = False
> 
>     async def _init_chat(self) -> DialogEntity:
>         """Resolve target chat and initialize tracking"""
>         chat = await self.chat_resolver.resolve(self.settings.tg.chat)
>         if not chat:
>             raise ValueError("🚫 Target chat not found")
> 
>         # Start channel difference polling
>         if self.settings.tg.without_joining_chat:
>             await self._start_channel_difference_polling(chat)
> 
>         return chat
> 
>     async def _start_channel_difference_polling(self, chat: DialogEntity) -> None:
>         """Maintain active subscription to chat updates"""
>         input_channel = InputChannel(channel_id=chat.id, access_hash=chat.access_hash)
> 
>         async def poller() -> None:
>             state: State = await self.client(GetStateRequest())
>             print(state)
>             pts = state.pts
>             while self.running:
>                 try:
>                     diff = await self.client(
>                         GetChannelDifferenceRequest(
>                             channel=input_channel, filter=ChannelMessagesFilterEmpty(), pts=pts, limit=100
>                         )
>                     )
> 
>                     print("Send Difference")
>                     timeout = diff.timeout or 1
> 
>                     if isinstance(diff, ChannelDifference):
>                         pts = diff.pts
> 
>                         if diff.final:
>                             await asyncio.sleep(timeout)
>                         else:
>                             continue
> 
>                     elif isinstance(diff, ChannelDifferenceTooLong):
>                         await asyncio.sleep(timeout)
> 
>                     else:
>                         await asyncio.sleep(timeout)
> 
>                 except FloodWaitError as e:
>                     wait_time = e.seconds + 2
>                     print(f"Flood wait: sleeping {wait_time} seconds")
>                     await asyncio.sleep(wait_time)
> 
>                 except Exception as e:
>                     print(f"Channel difference error: {e}", traceback.print_exception(e))
>                     await asyncio.sleep(20)
> 
>         asyncio.create_task(poller())
> 
>     async def _message_handler(self, event: events.NewMessage.Event) -> None:
>         print(f"Message: {event.message.message[:50]}")
>         """Handle new message events"""
> 
>     async def run(self) -> None:
>         """Start real-time monitoring"""
>         if not self.client.is_connected():
>             await self.client.connect()
> 
> 
>         self.active_chat = await self._init_chat()
>         self.running = True
> 
>         print(f"✅ Starting real-time monitoring in chat: {getattr(self.active_chat, 'title', 'Unknown')}")
> 
>         # Register event handler
>         self.client.add_event_handler(self._message_handler, events.NewMessage(chats=self.active_chat.id))
> 
>         await self.client.run_until_disconnected()
> 
>     async def stop(self) -> None:
>         """Stop monitoring"""
>         self.running = False
> Eventually everything worked. But then I joined this chat and started monitoring without `GetChannelDifferenceRequest`, as a result, the handler stopped receiving people's messages, only posts from the channel (in fact, I monitor channel comments).
> 
> I guess it's the same problem. Okay, I'll work with custom polling. He has a timeout of 30 seconds and events are starting to come to the handlers from there

Hi, the same thing happened to me just yesterday. I spent all day researching today, and the only solutions I found were using custom polling or keeping the Telegram application open. Since I use a VPS with Windows Server, I can keep the Telegram application open with my account while running my code on the same VPS, so my problem is now solved. I’m not sure how useful this will be for you.

**Comment by max0wn** [comment]
Same problem. Sometimes it triggers in relation to the same channel that didn't trigger before. First time works, second time it doesn't, third time it works again. Too weird

**Comment by BIBIYES** [comment]
> 更新：当 Telethon 正在运行时，如果在监控的频道中发送了一条消息，但没有触发 `events.NewMessage` 事件。如果打开该频道并在 Telegram 应用中（使用与 telethon 运行相同的用户账户）阅读该消息，则可以手动触发该事件。一旦打开频道并阅读消息，telethon 会立即触发该事件。

"When I start the program, some channels and groups do not trigger events.NewMessage. However, when I open the channel on my phone, events.NewMessage is triggered."

**Comment by alexeyhimself** [comment]
Same problem. Lasts for several weeks already. Delay is from 1 to 15 minutes.

**Comment by IvanSelianto** [comment]
The same issue still exists. I am encoruntering with that constantly.

**Comment by Wretnuh** [comment]
Is this going to be solved?? I'm experiencing same issue...

**Comment by alexeyhimself** [comment]
I solved this by adjusting:
```
NO_UPDATES_TIMEOUT = 15 * 60 
```
in `telethon/_updates/messagebox.py` to `1 * 60`.

Works well for 3 months already. More details in [this reply](https://github.com/LonamiWebs/Telethon/issues/4345#issuecomment-2098890913).

**Comment by Lonami** [comment]
Hi, I'm growing tired of GitHub, so I intend to move to https://codeberg.org/Lonami/Telethon. If the issue still matters to you, please reopen it there. Thanks.
